name = "yay"
version = "1.0.0"

licences = ["MIT"]

description = "A Gleam YAML parser supporting both Erlang and JavaScript targets."

repository = { type = "github", user = "Brickell-Research", repo = "yay" }
links = []

target = "erlang"

[erlang]
extra_applications = ["yamerl"]

[javascript]
runtime = "deno"

[javascript.deno]
allow_read = true

[dependencies]
gleam_stdlib = ">= 0.54.0 and < 2.0.0"
yamerl = ">= 0.10.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
