name = "glaml_extended"
version = "3.0.6"

licences = ["MIT"]

description = "A Gleam YAML parser supporting both Erlang and JavaScript targets based on a fork of glaml."

repository = { type = "github", user = "Brickell-Research", repo = "glaml_extended" }
links = []

target = "erlang"

[erlang]
extra_applications = ["yamerl"]

[dependencies]
gleam_stdlib = ">= 0.54.0 and < 2.0.0"
yamerl = ">= 0.10.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
